update tests

diff --git a/tools/dmenu-killall b/tools/dmenu-killall
--- a/tools/dmenu-killall
+++ b/tools/dmenu-killall
@@ -73,5 +73,8 @@ if [ -z "${process_name}" ]; then
     _die
 else
     error_msg="$(kill -9 $(pgrep -x "${process_name}") 2>&1 1>/dev/null)"
-    [ "${?}" != X"0" ] && _notify "Error" "${error_msg}"
+    if [ X"${?}" != X"0" ]; then
+        _notify "Error" "${error_msg}"
+        exit 1
+    fi
 fi
diff --git a/tools/dmenu-mpd b/tools/dmenu-mpd
--- a/tools/dmenu-mpd
+++ b/tools/dmenu-mpd
@@ -67,9 +67,10 @@ fi
 if [ -z "${song}" ]; then
     _die
 else
-    song="$(mpc playlist | awk '{if($0 == "'"${song}"'") {print NR}}')"
-    if [ -n "${song}" ]; then
-        error_msg="$(mpc play "${song}" 2>&1 1>/dev/null)"
-        [ "${?}" != X"0" ] && _notify "Error" "${error_msg}"
+    song="$(mpc playlist | awk '{if($0 == "'"${song}"'") {print NR}}')" || exit 1
+    error_msg="$(mpc play "${song}" 2>&1 1>/dev/null)"
+    if [ X"${?}" != X"0" ]; then
+        _notify "Error" "${error_msg}"
+        exit 1
     fi
 fi
diff --git a/tools/dmenu-vbox b/tools/dmenu-vbox
--- a/tools/dmenu-vbox
+++ b/tools/dmenu-vbox
@@ -69,5 +69,8 @@ if [ -z "${vboxmachine}" ]; then
     _die
 else
     error_msg="$(vboxmanage -q startvm "${vboxmachine}" --type gui 2>&1 1>/dev/null)"
-    [ "${?}" != X"0" ] && _notify "Error" "${error_msg}"
+    if [ X"${?}" != X"0" ]; then
+        _notify "Error" "${error_msg}"
+        exit 1
+    fi
 fi
